kind: Namespace
apiVersion: v1
metadata:
  name: appteam2-app2-ns
  labels:
    name: appteam2-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: appteam2-app2-ns
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: app
        image: dansregwu3.azurecr.io/core/app:v5.18
        ports:
          - containerPort: 80
            name: http-secure-80
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: appteam2-app2-ns
  labels:
    app.kubernetes.io/name: db
spec:
  hostname: mastersql01
  subdomain: sqldomain
  containers:
  - name: db
    image: dansregwu3.azurecr.io/core/db:v2.3
    ports:
      - containerPort: 3306
        name: mysql-3306

---
apiVersion: v1
kind: Service
metadata:
  name: sqldomain
  namespace: appteam2-app2-ns
spec:
  selector:
    app.kubernetes.io/name: db
  ports:
  - name: db-port1
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: appdomain
  namespace: appteam2-app2-ns
spec:
  selector:
    app.kubernetes.io/name: app
  type: LoadBalancer
  ports:
  - name: app-port1
    protocol: TCP
    port: 80
    targetPort: 80